### ISSUE TITLE
Link room error 500

### ISSUE THREAD

**Issue by MrTerr1riym** [Lost-MSth/Arcaea-server#119]
Hello, I have encountered a problem that I don't know how to solve
Just in case I say that ports are open, ip is correct (in both config.py)
I try to run link play, but I get an error in the console and the game says "Cloud not connected to online server."
How can this be solved?

Arcaea 4.4.2c
Server v2.11.2
![-231163_temp](https://github.com/Lost-MSth/Arcaea-server/assets/64203805/1577168e-0aaf-45ad-aedf-f3671fdf3a87)

**Comment by Lost-MSth** [comment]
I remind two reasons:

1. The subprocess is not running. However you said the port is open. Please check the port via `lsof` or `netstat`.
2. The firewall is not open for the port. If you use the cloud server, maybe you need to open specific port in the admin leadboard of the server.

**Comment by MrTerr1riym** [comment]
I still can't figure it out....
Yes I'm using a vps
Ports opened via "ufw allow .../upd and .../tcp"
If I start only the server and try to run link play separately I get an error
Traceback (most recent call):
 File "/root/v2.11.2/linkplay_server/main.py", line 6, in <module>
  from .aes import decrypt, encrypt
ImportError: attempted relative import with no known parent package

**Comment by Lost-MSth** [comment]
If you didn't change the config file, the port which need to be open is `UDP 10900` and `TCP 80`. Well, from the first pic I think the problem is that the main server cannot connect to the linkplay server via port `TCP 10901`. You can run `telnet 127.0.0.1 10901` in the server to check whether the linkplay server is running or the port is banned or not.

Use `run_linkplay_server.py` to run the linkplay server singly.
