### ISSUE TITLE
Ptt system

### ISSUE THREAD

**Issue by MrTerr1riym** [Lost-MSth/Arcaea-server#136]
Hello, could you change the capacity system a potential?
It's not nice when you try to clear ftr 11 and score 9'700, even though it was 9'650, and you get ptt taken away because - yes
Please make it so that if the record was at least 00'005'000+ better (in the global top), the ptt is not taken away

**Comment by Lost-MSth** [comment]
You want to make PTT not decrease when breaking historic records, right?

At least currently, I don't have any ideas about adding this feature, because it is not in the offical server. Surely we haven't known all about the PTT system. If you think there are the new mechanisms, show me your evidence.

However, this feature is not complex. You can change the code by yourself. In line 481 & 485 of `core/score.py`, you can see a flag `first_protect_flag` and a compare between new and old scores, so just making flag true in that case can protect your PTT.

**Comment by MrTerr1riym** [comment]
I can't provide evidence that such a system exists in Arcaea but I can't recall a single time when I had a score of 9'100 and improved it to 9'440~ on a song (ftr 9) without my ptt dropping (I was playing on a friend's account at the time with ~12.20 ptt
![IMG_20231026_132322](https://github.com/Lost-MSth/Arcaea-server/assets/64203805/7574be8d-7e07-491a-a718-3007247db032)
![IMG_20231026_132239](https://github.com/Lost-MSth/Arcaea-server/assets/64203805/0e22be3a-e735-4fec-ace6-70852389c793)
![IMG_20231026_132310](https://github.com/Lost-MSth/Arcaea-server/assets/64203805/3a1a4bef-939c-4612-9cb2-442ab72a4b93)

It is unpleasant...

**Comment by MrTerr1riym** [comment]
Changing score.py seemed to help
Thanks
