### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#154]
Would there be any video guides, or text guides that I can follow to open my own private server? It's too hard for me to start everything from scratch, I would appreciate your help.

**Comment by Lost-MSth** [comment]
I think I have given all the information you needed to set up the server.

If you mean how to let the client connect to the server, this is not a suitable place to discuss this issue. Moreover, it is based on your versatile ablilities. You can get the answer from the search engine.

I would prefer you to raise some detailed questions instead of such a vague and meaningless one.

**Comment by rlarhsid** [comment]
Ok, sorry. I'll try to find ways to link the server and the client by myself, thanks.
