### ISSUE TITLE
Client crashes when loading up a newly added song while being online, but doesn't when offline.

### ISSUE THREAD

**Issue by JonathanLorikon** [Lost-MSth/Arcaea-server#169]
I have added some content to the game via [Arcaea-Bundler](https://github.com/Lost-MSth/Arcaea-Bundler)'s cb files and also added them to the server database, which then results in successful downloads. Although the client downloads it correctly, it crashes upon loading a song whilst connected to the server. However, it is playable offline without any issues? Any idea what causes this? Is this client-side or server-related?

**Comment by Lost-MSth** [comment]
Many possible reasons. It is easy to check whether it is caused by server or not. Notice the server's console log at the crashing timing. If there are no request, it will be more likely a client issue.

Based on your description, the crash happened when loading one chart. I think it is a client issue because of no request at that time, and my experience tells me that may be caused by hard-coded songs. The client must contain some specific songs and packs, or the client cannot work correctly online.
