### ISSUE TITLE
为什么尝试在arcsong.db中添加歌曲信息时会显示Error: no such table: chart呢？

### ISSUE THREAD

**Issue by Cinchonine** [Lost-MSth/Arcaea-server#68]
为什么尝试在arcsong.db中添加歌曲信息时会显示Error: no such table: chart呢？

Emm...I've just followed your mannual. As in ver.2.9 there is no song data in "arcsong.db", I want to add some in it, but I just can't...
![{239CF1E2-5C8A-4F4F-86EE-0B4E6F455EA9} png](https://user-images.githubusercontent.com/112184192/186923301-38b4571f-a07c-4e42-9d3c-6093552e6ef6.jpg)
或者我可以使用以前版本（2.8及以下）的数据库嘛？
好像服务器运行正常的说
![批注 2022-08-26 221429](https://user-images.githubusercontent.com/112184192/186923925-344f8a1e-d991-4cc7-976f-6f068ed1d709.jpg)

**Comment by Cinchonine** [comment]
对了，我不是很懂sqlite。。。
python也是学校教的（笑）
所以有可能是**我的问题**

**Comment by Lost-MSth** [comment]
哦哦，我更新wiki没更新全，那个对tag 2.9之前有效

在tag 2.9的更新公告中说明了不再提供歌曲数据，可能很难联想到是放弃了`arcsong.db`

在readme里面最底下也说明了一遍


**重复一下**：在以后的版本中不再使用单独的`arcsong.db`，而是整合在`chart`表中，可以使用`tools`下的py脚本从旧的`arcsong.db`进行导入

Since 2.9, `arcsong.db` will not be used. The song data will be put in the `chart` table. You can use the py file under the `tools` folder to import old data of `arcsong.db`.

**Comment by Cinchonine** [comment]
好的谢谢，懂了。
